[package]
name = "mmorpg-client-adapter"
version = "0.1.0"
edition = "2024"
publish = false

[workspace]

[dependencies]
mmorpg-client-model = { path = "../mmorpg-client-model" }
mmorpg-client-protocol = { path = "../mmorpg-client-protocol" }
mmorpg-content = { path = "../mmorpg-content" }
mmorpg-core = { path = "../mmorpg-core" }

[lints.rust]
unsafe_code = "forbid"
